"""
Generates IFOA_AI_Papers_<timestamp>.csv per ifoa_downloads/prompt.txt.

Extraction method: 10 PDFs extracted via parallel sub-agents reading PDFs.
This script assembles those results into the final CSV.

Extraction timing log (2026-08-15 session):
  - Start checkpoint: 08:54:49. End checkpoint: 08:55:39 (~50s wall-clock for parallel agents).
  - Total sub-agent token usage across all 10: ~397,347 tokens.
"""

import csv
import time
from datetime import datetime
from zoneinfo import ZoneInfo

HEADER = [
    "S/N",
    "Topic",
    "Sub-topic",
    "URL",
    "Description",
    "Comments",
    "Date of publication (dd/mm/yyyy)",
    "Authors",
    "Area of practice",
    "Dataset (real/simulated; granularity)",
    "Dataset modality",
    "Code available? (language; link if any)",
    "ML/AI technique (granular label)",
    "Learning paradigm & task (supervised/unsupervised/etc; regression/classification)",
]

ROWS = [
    [
        "1", "Operational applications", "Performance reporting / Risk reporting", "N/A",
        "This article explores the transformative potential of AI agents in actuarial modelling, "
        "examining their current applications and far-reaching implications for the actuarial "
        "profession over the coming decade. The paper draws parallels between AI-driven automation "
        "in software engineering and its anticipated impact on actuarial work.",
        "Article is published on Substack platform (not traditional paper); curated conceptual "
        "piece rather than empirical research",
        "08/05/2025", "Daniel Craig Ramsay", "N/A", "N/A (conceptual/no dataset)", "N/A",
        "No / not stated",
        "LLM agents; multi-agent systems (monolithic, orchestrated multi-agent, hierarchical); "
        "generative AI for code automation",
        "N/A; not applicable",
    ],
    [
        "2", "Operational applications", "Survey/qualitative analysis of GenAI adoption", "N/A",
        "Survey of actuaries on current GenAI adoption, usage patterns, and future expectations "
        "for generative AI in the actuarial profession, conducted by the IFoA GenAI Working Party "
        "in early 2025.",
        "This is a survey/qualitative document, not an empirical research paper. Forced fit to "
        "\"Operational applications\" as it addresses practical workplace adoption and "
        "implementation strategies.",
        "22/05/2025", "Betty Zhu; Daniel Craig Ramsay; Disha Dagli",
        "Life; General Insurance; Pensions",
        "Real; survey responses from actuarial professionals across various sectors and "
        "seniority levels",
        "Survey", "No / not stated",
        "Survey/qualitative analysis of GenAI adoption; LLM usage patterns (ChatGPT, Copilot, "
        "etc.); prompt engineering; RAG; framework usage (TensorFlow, LangChain, PyTorch); "
        "neural network architectures (RNNs, LSTMs, GANs, VAEs)",
        "N/A; survey/qualitative",
    ],
    [
        "3", "Operational applications", "Claims Management", "https://ssrn.com/abstract=4543652",
        "Paper introduces applications of LLMs such as GPT-4 to insurance and actuarial work, "
        "demonstrating direct applications in claims processing through automated information "
        "extraction, classification, and sentiment analysis, and indirect assistance for coding, "
        "problem-solving, and reporting.",
        "Theoretical paper with decision frameworks; case studies use simulated data generated by "
        "LLMs; strong focus on claims workflow automation; no novel ML technique.",
        "17/08/2023", "Caesar Balona", "General Insurance (GI)", "N/A (simulated/no dataset)",
        "N/A", "Yes / Python; https://github.com/cbalona/actuarygpt-code",
        "GPT-4 (OpenAI API); prompt engineering; few-shot learning; entity recognition; "
        "sentiment analysis",
        "N/A (conceptual/no training); text generation and classification",
    ],
    [
        "4", "Operational applications", "Pipeline orchestration framework", "N/A",
        "Modular framework for building machine learning pipelines in insurance, covering five "
        "modules: business problem definition, data handling, modelling, deployment, and "
        "monitoring. Framework emphasizes speed, performance, risk management, integration, and "
        "scalability (SPRISS).",
        "This is a presentation/framework document, not a research paper. Taxonomy fit: "
        "\"Operational applications\" is closest match, as focus is on ML pipeline implementation "
        "and management in insurance operations rather than forecasting, portfolio risk, or "
        "regulatory considerations.",
        "14/09/2020", "John Ng", "Actuarial; Insurance", "N/A (conceptual/no dataset)", "N/A",
        "No / not stated",
        "N/A (framework/methodology); various ML algorithms discussed (Random Forest, XGBoost, "
        "Neural Networks, Linear Regression, GLM, SVM, K-NN, Decision Trees, NLP) but not applied "
        "to specific dataset",
        "N/A; framework/methodology",
    ],
    [
        "5", "Operational applications", "Stress testing", "N/A",
        "This paper describes statistical methods for testing computer-generated data from known "
        "models, contrasting laboratory testing approaches with conventional out-of-sample "
        "testing to assess model robustness and identify weaknesses.",
        "Paper emphasizes ersatz surrogate model testing via generated data rather than historic "
        "back-testing; best fit is operational stress-testing rather than forecasting; "
        "methodologically sound for actuarial model validation.",
        "13/10/2016", "Stuart Jarvis; James Sharpe; Andrew D Smith",
        "Actuarial risk management; pension/insurance capital adequacy",
        "Simulated; multiple reference datasets and synthetic scenarios", "Tabular",
        "No / not stated",
        "Statistical distribution fitting (exponential, Pareto, Bayesian); Monte Carlo scenario "
        "generation; bootstrap resampling",
        "Unsupervised; scenario generation and model validation",
    ],
    [
        "6", "Forecasting & Asset Projections", "Time series forecasting", "N/A",
        "The IFoA's Data Science, Sustainability and Climate Change Working Party analyses the "
        "S&P Green Bond Index using time series neural networks (CNNs, LSTMs, GRUs) and XGBoost "
        "to forecast or replicate bond index behaviour.",
        "Introductory paper; foundation for future analysis. Deliberately excludes stationarity "
        "and market correlation analysis.",
        "01/12/2023", "Debashish Dey; IFoA's Data Science, Sustainability and Climate Change "
        "Working Party",
        "Investment", "Real; daily time series of S&P Green Bond Index", "Time series",
        "Yes / Python; Keras, TensorFlow, Optuna; Google Colab environment used",
        "LSTM; CNN; GRU; XGBoost", "Supervised; regression/forecasting",
    ],
    [
        "7", "Forecasting & Asset Projections", "Time series forecasting", "N/A",
        "This article presents an application of the N-BEATS neural network architecture to "
        "forecast the S&P Green Bond Index, demonstrating state-of-the-art deep learning "
        "techniques for financial time series prediction.",
        "This is an IFoA working party article/summary; the detailed technical report \"Time "
        "series analysis of GSS bonds: Part 2\" is referenced but not included in this PDF. This "
        "article itself does not present original research but rather summarizes and "
        "contextualizes the approach.",
        "07/08/2024", "Debashish Dey; IFoA's Data Science, Sustainability and Climate Change "
        "Working Party",
        "Investment", "Real; daily time series of S&P Green Bond Index", "Time series",
        "No / not stated",
        "N-BEATS (Neural Basis Expansion Analysis Time Series) deep neural forecasting "
        "architecture with Keras and TensorFlow implementation; hyperparameter optimization via "
        "Optuna",
        "Supervised; regression/time series forecasting",
    ],
    [
        "8", "Ethics & Regulatory considerations", "PRA/FCA considerations", "N/A",
        "Conference paper preview on using NLP and machine learning to extract intelligence from "
        "company financial disclosures and prospectuses for investment analysis, credit ratings, "
        "and ESG screening in the Asian financial market.",
        "Conference preview paper, not a research paper; focuses on applications (named entity "
        "recognition on disclosures, quantitative modeling) rather than methodological "
        "innovation. Taxonomy fit: reg-tech context aligns with regulatory/compliance "
        "considerations.",
        "01/09/2023", "Muqiu Liu; Estelle Xu; Chengcheng Wang", "Investment/Asset Management",
        "N/A (conceptual with illustrative examples)",
        "Text (financial disclosures, prospectuses, annual reports)", "No / not stated",
        "Named entity recognition (NER); text classification; quantitative modeling",
        "Unsupervised; named entity recognition on financial text",
    ],
    [
        "9", "Operational applications",
        "Performance reporting / Risk reporting / Other Management Info", "N/A",
        "A comprehensive working party report exploring machine learning applications across "
        "actuarial practice areas, with four case studies demonstrating supervised learning "
        "techniques for interest rate forecasting, marine hull pricing, exposure management, and "
        "mortality analysis.",
        "Institute and Faculty of Actuaries (IFoA) working party report; conclusions inconclusive "
        "for most case studies; exploratory scope as starting point for further research.",
        "30/01/2018",
        "Alex Panlilio; Ben Canagaretna; Steven Perkins; Valerie du Preez; Zhixin Lim",
        "Multiple (Insurance pricing, Investment, Pension scheme valuation, Exposure management)",
        "Real actuarial data; policy/claims-level and exposure-level granularity", "Tabular",
        "No / not stated",
        "Multiple techniques: Sentiment analysis with supervised learning (NLP/text); Generalised "
        "Linear Model; Random Forest; Extreme Gradient Boosting; Bayesian Structural Time Series",
        "Supervised; regression and classification",
    ],
    [
        "10", "Portfolio & Risk Management", "Scenario analysis",
        "https://doi.org/10.1017/S1357321718000181",
        "Survey of the evolution of economic scenario generators used in insurance and pension "
        "fund management, covering stochastic modelling approaches from random walks to "
        "market-consistent models.",
        "Report by Extreme Events Working Party, published in British Actuarial Journal; "
        "comprehensive historical review covering 40-50 years of evolution in ESG methodology.",
        "22/02/2018", "P. Jakhria; R. Frankland; S. Sharp; A. Smith; A. Rowe; T. Wilkins",
        "Life insurance; Pension schemes",
        "Simulated; economic scenario paths (multi-year Monte Carlo simulations)",
        "Time series; tabular", "No / not stated",
        "Monte Carlo scenario simulation; stochastic time series models; market-consistent "
        "models; Value-at-Risk (VaR) models; Brownian motion; random walk models; ARCH/GARCH "
        "models",
        "N/A; simulation-based and conceptual survey",
    ],
]


def main() -> None:
    start = time.perf_counter()
    # Local London time (auto BST/GMT), not system-implicit - matches
    # the user's wall clock regardless of the host's own timezone.
    timestamp = datetime.now(ZoneInfo("Europe/London")).strftime("%Y%m%d_%H%M%S")
    out_path = f"IFOA_AI_Papers_{timestamp}.csv"

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(HEADER)
        writer.writerows(ROWS)

    elapsed = time.perf_counter() - start
    print(f"Wrote {len(ROWS)} rows to {out_path} in {elapsed:.3f}s")


if __name__ == "__main__":
    main()
